export enum RouterEndpoints {
  RESOURCES = 'resource',
  DATASETS = 'dataset',
  PROVIDERS = 'institution',
  APPLICATIONS = 'application',
  ARTICLES = 'article',
  HELP = 'help',
  EDUCATION = 'education',
  FAQ = 'faq',
  KNOWLEDGE_BASE = 'knowledgebase',
  MULTIMEDIA_TRAINING = 'multimedia-training',
  USEFUL_MATERIALS = 'useful-materials',
  EVENTS = 'events',
  PREVIEW = 'preview',
  LOGIN = 'user/login',
  SHOWCASE = 'showcase',
  NEWS = 'news',
}
