import { Injectable } from '@angular/core';
import { combineLatest, Observable, of } from 'rxjs';
import { delay, map } from 'rxjs/operators';

import { RestService } from '@app/services/rest.service';
import { StringHelper } from '@app/shared/helpers/string.helper';
import { ForumBadge, ForumCategory, ForumNotification, ForumNotificationWithBadge, ForumTopic, ForumTopicWithCategory } from '@app/user/forum/forum.enum';

/**
 * Forum Service
 */
@Injectable({
    providedIn: 'root'
})
export class ForumService extends RestService {

    /**
     * List of all badges
     */
    badges$: Observable<ForumBadge[]>;
    
    /**
     * Latest notifications
     */
    notifications$: Observable<ForumNotification[]>;

    /**
     * Topic/post categories
     */
    categories$: Observable<ForumCategory[]>;

    /**
     * Latest topics
     */
    latestTopics$: Observable<ForumTopic[]>;

    /**
     * Gets badges
     * @returns {Observable<ForumBadge[]>} badges 
     */
    getBadges(): Observable<ForumBadge[]> {
        // https://forum.szkolenia.dane.gov.pl/badges.json
        const badgesResponse = {
            "badges": [
                {
                    "id": 2,
                    "name": "Uczestnik",
                    "description": "<a href=\"https://blog.discourse.org/2018/06/understanding-discourse-trust-levels/\">Przyznano</a>możliwość zapraszania, wysyłania wiadomości grupowych, więcej polubień",
                    "grant_count": 0,
                    "allow_title": false,
                    "multiple_grant": false,
                    "icon": "fa-user",
                    "image": null,
                    "listable": true,
                    "enabled": true,
                    "badge_grouping_id": 4,
                    "system": true,
                    "long_description": "Ta odznaka jest przyznawana za zdobycie 2. poziomu zaufania. Dziękujemy za prawdziwe włączenie się w naszą społeczeność poprzez udzielanie się przez ostatnich kilka tygodni. Możesz teraz wysyłać zaproszenia ze swojej strony użytkownika lub z tematów, tworzyć konwersacje grupowe i otrzymywać dziennie więcej polubień.\n",
                    "slug": "uczestnik",
                    "has_badge": false,
                    "manually_grantable": false,
                    "badge_type_id": 3
                },
                {
                    "id": 3,
                    "name": "Stały bywalec",
                    "description": "<a href=\"https://blog.discourse.org/2018/06/understanding-discourse-trust-levels/\">Przyznano</a>możliwość zmiany kategorii i nazwy, tworzenie linków dofollow, wiki, więcej polubień",
                    "grant_count": 0,
                    "allow_title": true,
                    "multiple_grant": false,
                    "icon": "fa-user",
                    "image": null,
                    "listable": true,
                    "enabled": true,
                    "badge_grouping_id": 4,
                    "system": true,
                    "long_description": "Ta odznaka jest przyznawana za zdobycie 3. poziomu zaufania. Dziękujemy za bycie stałym bywalcem naszej społeczności przez ostatnich kilka miesięcy. Jesteś jednym z najbardziej aktywnych czytelników i masz realny wkład w ulepszanie naszej społeczności. Możesz teraz rekategoryzować tematy i zmieniać ich nazwy, używać skuteczniejszych metod flagowania, korzystać z dostępu do Salonu oraz otrzymywać o wiele więcej polubień dziennie.\n",
                    "slug": "staly-bywalec",
                    "has_badge": false,
                    "manually_grantable": false,
                    "badge_type_id": 2
                },
                {
                    "id": 4,
                    "name": "Weteran",
                    "description": "<a href=\"https://blog.discourse.org/2018/06/understanding-discourse-trust-levels/\">Przyznano</a> możliwość globalnej edycji, przypinania, zamykania, archiwizacji, dzielenia i scalania tematów oraz więcej polubień",
                    "grant_count": 0,
                    "allow_title": true,
                    "multiple_grant": false,
                    "icon": "fa-user",
                    "image": null,
                    "listable": true,
                    "enabled": true,
                    "badge_grouping_id": 4,
                    "system": true,
                    "long_description": "Ta odznaka jest przyznawana za zdobycie 4. poziomu zaufania. Jesteś wybranym przez zespół administracyjny weteranem i stawiasz dobry przykład reszcie społeczności poprzez swoje akcje i wypowiedzi. Możesz edytować wszystkie wpisy i dokonywać akcji typowych dla moderatorów: przypinania, zamykania, usuwanie z list, archiwizowania, dzielenia i scalania tematów.\n",
                    "slug": "weteran",
                    "has_badge": false,
                    "manually_grantable": false,
                    "badge_type_id": 1
                },
                {
                    "id": 17,
                    "name": "Czytelnik",
                    "description": "Przeczytanie każdego odpowiedzi w temacie z ponad 100 wpisami",
                    "grant_count": 0,
                    "allow_title": false,
                    "multiple_grant": false,
                    "icon": "fa-certificate",
                    "image": null,
                    "listable": true,
                    "enabled": true,
                    "badge_grouping_id": 1,
                    "system": true,
                    "long_description": "Ta odznaka jest przyznawana, gdy po raz pierwszy przeczytasz dłuższy temat z więcej niż 100 wpisami. Dokładne czytanie konwersacji pozwala na śledzenie dyskusji, zrozumienie różnych punktów widzenia i prowadzi do bardziej interesującej konwersacji. Im więcej czytasz, tym lepsza staję się konwersacja. Lubimy powtarzać, że czytanie to właśnie fundament! :slight_smile:\n",
                    "slug": "czytelnik",
                    "has_badge": false,
                    "manually_grantable": false,
                    "badge_type_id": 3
                },
                {
                    "id": 13,
                    "name": "Pierwsza flaga",
                    "description": "Zgłoszenie wpisu",
                    "grant_count": 0,
                    "allow_title": false,
                    "multiple_grant": false,
                    "icon": "fa-certificate",
                    "image": null,
                    "listable": true,
                    "enabled": true,
                    "badge_grouping_id": 1,
                    "system": true,
                    "long_description": "Ta odznaka jest przyznawana za pierwszym oflagowaniem posta. Dzięki flagowaniu wszyscy pomagamy utrzymać to miejsce przyjaznym dla wszystkich. Jeśli zauważysz jakiekolwiek posty, które z jakiegokolwiek powodu wymagają uwagi moderatora, nie wahaj się ich oflagować. Jeśli widzisz problem, :flag_black: oflaguj go!\n",
                    "slug": "pierwsza-flaga",
                    "has_badge": false,
                    "manually_grantable": false,
                    "badge_type_id": 3
                },
                {
                    "id": 25,
                    "name": "Promotor",
                    "description": "Zaproszenie użytkownika",
                    "grant_count": 0,
                    "allow_title": false,
                    "multiple_grant": false,
                    "icon": "fa-user-plus",
                    "image": null,
                    "listable": true,
                    "enabled": true,
                    "badge_grouping_id": 2,
                    "system": true,
                    "long_description": "Ta odznaka jest przyznawana, gdy zaprosisz kogoś do społeczności za pomocą przycisku zapraszania na stronie użytkownika lub w dolnej części tematu. Zapraszanie znajomych, którzy mogą być zainteresowani konkretnymi dyskusjami, to świetny sposób na wprowadzenie nowych osób do naszej społeczności, więc dzięki!\n",
                    "slug": "promotor",
                    "has_badge": false,
                    "manually_grantable": false,
                    "badge_type_id": 3
                },
                {
                    "id": 26,
                    "name": "Działacz",
                    "description": "Zaproszenie 3 użytkowników",
                    "grant_count": 0,
                    "allow_title": false,
                    "multiple_grant": false,
                    "icon": "fa-user-plus",
                    "image": null,
                    "listable": true,
                    "enabled": true,
                    "badge_grouping_id": 2,
                    "system": true,
                    "long_description": "Ta odznaka jest przyznawana, gdy zaprosiłeś 3 osoby, które następnie spędziły wystarczająco dużo czasu na stronie, aby stać się regularnymi użytkownikami. Żywa społeczność potrzebuje regularnego napływu nowych osób, które regularnie uczestniczą i dodają swoje opinie do dyskusji.\n",
                    "slug": "dzialacz",
                    "has_badge": false,
                    "manually_grantable": false,
                    "badge_type_id": 2
                },
                {
                    "id": 27,
                    "name": "Mistrz",
                    "description": "Zaproszono 5 użytkowników",
                    "grant_count": 0,
                    "allow_title": false,
                    "multiple_grant": false,
                    "icon": "fa-user-plus",
                    "image": null,
                    "listable": true,
                    "enabled": true,
                    "badge_grouping_id": 2,
                    "system": true,
                    "long_description": "Ta odznaka jest przyznawana, gdy zaprosisz 5 osób, które następnie spędziły w witrynie wystarczająco dużo czasu, aby zostać pełnoprawnymi użytkownikami. Wow! Dziękujemy za rozszerzenie różnorodności naszej społeczności o nowe osoby!\n",
                    "slug": "mistrz",
                    "has_badge": false,
                    "manually_grantable": false,
                    "badge_type_id": 1
                },
                {
                    "id": 12,
                    "name": "Pierwsze udostępnienie",
                    "description": "Udostępniono wpis",
                    "grant_count": 0,
                    "allow_title": false,
                    "multiple_grant": false,
                    "icon": "fa-certificate",
                    "image": null,
                    "listable": true,
                    "enabled": true,
                    "badge_grouping_id": 1,
                    "system": true,
                    "long_description": "Ta odznaka jest przyznawana, kiedy po raz pierwszy dzielisz się linkiem odpowiedzi albo tematu, posługując się przyciskiem \"Prześlij\". Dzielenie się linkami to znakomity sposób na pokazanie ciekawej dyskusji innym i na powiększenie grona znajomych.\n",
                    "slug": "pierwsze-udostepnienie",
                    "has_badge": false,
                    "manually_grantable": false,
                    "badge_type_id": 3
                },
                {
                    "id": 21,
                    "name": "Niezłe udostępnienie",
                    "description": "Udostępniono wpis z 25 unikalnymi odwiedzającymi.",
                    "grant_count": 0,
                    "allow_title": false,
                    "multiple_grant": true,
                    "icon": "fa-certificate",
                    "image": null,
                    "listable": true,
                    "enabled": true,
                    "badge_grouping_id": 2,
                    "system": true,
                    "long_description": "Ta odznaka przyznawana jest za udostępnienie linku, który został naciśnięty przez co najmniej 25 osób. Dziękujemy za rozpowszechnianie naszych konwersacji i tej społeczności.\n",
                    "slug": "niezle-udostepnienie",
                    "has_badge": false,
                    "manually_grantable": false,
                    "badge_type_id": 3
                },
                {
                    "id": 22,
                    "name": "Dobre udostępnienie",
                    "description": "Udostępniono wpis z 300 unikalnymi odwiedzającymi.",
                    "grant_count": 0,
                    "allow_title": false,
                    "multiple_grant": true,
                    "icon": "fa-certificate",
                    "image": null,
                    "listable": true,
                    "enabled": true,
                    "badge_grouping_id": 2,
                    "system": true,
                    "long_description": "Ta odznaka jest przyznawana za udostępnienie linku, który został kliknięty przez 300 zewnętrznych gości. Dobra robota! Pokazałeś świetną dyskusję kilku nowym osobom i pomogłeś tej społeczności się rozwijać.\n",
                    "slug": "dobre-udostepnienie",
                    "has_badge": false,
                    "manually_grantable": false,
                    "badge_type_id": 2
                },
                {
                    "id": 23,
                    "name": "Świetne udostępnienie",
                    "description": "Udostępniono wpis z 1000 unikalnych odwiedzających.",
                    "grant_count": 0,
                    "allow_title": false,
                    "multiple_grant": true,
                    "icon": "fa-certificate",
                    "image": null,
                    "listable": true,
                    "enabled": true,
                    "badge_grouping_id": 2,
                    "system": true,
                    "long_description": "Ta odznaka jest przyznawana za udostępnienie linku, który został kliknięty przez 1000 zewnętrznych gości. Wow! Wypromowałeś interesującą dyskusję wśród ogromnej liczby nowych odbiorców i pomogłeś nam w dużym stopniu rozwinąć naszą społeczność!\n",
                    "slug": "swietne-udostepnienie",
                    "has_badge": false,
                    "manually_grantable": false,
                    "badge_type_id": 1
                },
                {
                    "id": 9,
                    "name": "Autobiograf",
                    "description": "Wypełniono<a href=\"/my/preferences/profile\">profil</a>użytkownika",
                    "grant_count": 0,
                    "allow_title": false,
                    "multiple_grant": false,
                    "icon": "fa-certificate",
                    "image": null,
                    "listable": true,
                    "enabled": true,
                    "badge_grouping_id": 1,
                    "system": true,
                    "long_description": "Ta odznaka jest przyznawana za wypełnienie <a href=\"/my/preferences/profile\">profilu użytkownika</a>i wybranie zdjęcia profilowego. Dając się lepiej poznać i pokazując swoje zainteresowania czynisz społeczność lepszą i silniej związaną. Dołącz do nas!\n",
                    "slug": "autobiograf",
                    "has_badge": false,
                    "manually_grantable": false,
                    "badge_type_id": 3
                },
                {
                    "id": 5,
                    "name": "Powitanie",
                    "description": "Otrzymano polubienie",
                    "grant_count": 0,
                    "allow_title": false,
                    "multiple_grant": false,
                    "icon": "fa-certificate",
                    "image": null,
                    "listable": true,
                    "enabled": true,
                    "badge_grouping_id": 2,
                    "system": true,
                    "long_description": "Ta odznaka jest przyznawana za otrzymanie pierwszego polubienia przy wpisie. Gratulacje, napisałeś/napisałaś coś, co inni użytkownicy uznali za interesujące, fajne lub użyteczne!\n",
                    "slug": "powitanie",
                    "has_badge": false,
                    "manually_grantable": false,
                    "badge_type_id": 3
                },
                {
                    "id": 16,
                    "name": "Przeczytany przewodnik",
                    "description": "Przeczytaj <a href=\"/guidelines\">wytyczne dla społeczności</a>",
                    "grant_count": 1,
                    "allow_title": false,
                    "multiple_grant": false,
                    "icon": "fa-certificate",
                    "image": null,
                    "listable": true,
                    "enabled": true,
                    "badge_grouping_id": 1,
                    "system": true,
                    "long_description": "Ta odznaka jest przyznana za przeczytanie <a href=\"/guidelines\">wytycznych społeczności</a>. Przestrzeganie tych prostych zasad i dzielenie się nimi pomaga zbudować bezpieczną, zabawną i zrównoważoną społeczność dla wszystkich użytkowników. Zawsze pamiętaj, że po drugiej stronie ekranu jest inny człowiek, bardzo podobny do Ciebie. Bądź miły!\n",
                    "slug": "przeczytany-przewodnik",
                    "has_badge": true,
                    "manually_grantable": false,
                    "badge_type_id": 3
                },
                {
                    "id": 11,
                    "name": "Pierwsze polubienie",
                    "description": "Polubiono wpis",
                    "grant_count": 0,
                    "allow_title": false,
                    "multiple_grant": false,
                    "icon": "fa-certificate",
                    "image": null,
                    "listable": true,
                    "enabled": true,
                    "badge_grouping_id": 1,
                    "system": true,
                    "long_description": "Ta odznaka jest przyznawana, gdy po raz pierwszy polubisz wpis poprzez przycisk :heart:. Dokonywanie polubień jest świetnym sposobem aby poinformować członków społeczności, że ich wpis jest naprawdę interesujący, przydatny, fajny, zabawny. Dziel się miłością!\n",
                    "slug": "pierwsze-polubienie",
                    "has_badge": false,
                    "manually_grantable": false,
                    "badge_type_id": 3
                },
                {
                    "id": 10,
                    "name": "Edytor",
                    "description": "Pierwsza edycja",
                    "grant_count": 1,
                    "allow_title": false,
                    "multiple_grant": false,
                    "icon": "fa-certificate",
                    "image": null,
                    "listable": true,
                    "enabled": true,
                    "badge_grouping_id": 1,
                    "system": true,
                    "long_description": "Ta odznaka jest przyznawana, gdy po raz pierwszy edytujesz jeden ze swoich postów. Chociaż nie będziesz mógł edytować swoich postów na zawsze, zachęcamy do edycji - możesz poprawić formatowanie, naprawić drobne błędy lub dodać wszystko, co przegapiłeś, gdy pisałeś swój post po raz pierwszy. Edytuj, aby Twoje posty były jeszcze lepsze!\n",
                    "slug": "edytor",
                    "has_badge": true,
                    "manually_grantable": false,
                    "badge_type_id": 3
                },
                {
                    "id": 14,
                    "name": "Pierwszy link",
                    "description": "Dodano wewnętrzny link do innego tematu",
                    "grant_count": 0,
                    "allow_title": false,
                    "multiple_grant": false,
                    "icon": "fa-certificate",
                    "image": null,
                    "listable": true,
                    "enabled": true,
                    "badge_grouping_id": 1,
                    "system": true,
                    "long_description": "Ta odznaka jest przyznawana, kiedy po raz pierwszy podajesz link do innego tematu w odpowiedzi. Udostępnianie tematów pomaga innym czytającym w odnalezieniu powiązanych interesujących dyskusji, pokazując związki między tematami w obydwu kierunkach.\n",
                    "slug": "pierwszy-link",
                    "has_badge": false,
                    "manually_grantable": false,
                    "badge_type_id": 3
                },
                {
                    "id": 48,
                    "name": "Redaktor Wiki",
                    "description": "Pierwsza edycja Wiki",
                    "grant_count": 0,
                    "allow_title": false,
                    "multiple_grant": false,
                    "icon": "fa-certificate",
                    "image": null,
                    "listable": true,
                    "enabled": true,
                    "badge_grouping_id": 1,
                    "system": true,
                    "long_description": "Ta odznaka jest przyznawana za pierwszą edycję wpisu na wiki.\n",
                    "slug": "redaktor-wiki",
                    "has_badge": false,
                    "manually_grantable": false,
                    "badge_type_id": 3
                },
                {
                    "id": 6,
                    "name": "Niezła odpowiedź",
                    "description": "Otrzymano 10 polubień w odpowiedzi",
                    "grant_count": 0,
                    "allow_title": false,
                    "multiple_grant": true,
                    "icon": "fa-certificate",
                    "image": null,
                    "listable": true,
                    "enabled": true,
                    "badge_grouping_id": 3,
                    "system": true,
                    "long_description": "Ta odznaka jest przyznawana, gdy Twoja odpowiedź otrzyma 10 polubień. Twoja odpowiedź wywarła wrażenie na społeczności i pomogła posunąć rozmowę do przodu.\n",
                    "slug": "niezla-odpowiedz",
                    "has_badge": false,
                    "manually_grantable": false,
                    "badge_type_id": 3
                },
                {
                    "id": 7,
                    "name": "Dobra odpowiedź",
                    "description": "Otrzymano 25 polubień w odpowiedzi",
                    "grant_count": 0,
                    "allow_title": false,
                    "multiple_grant": true,
                    "icon": "fa-certificate",
                    "image": null,
                    "listable": true,
                    "enabled": true,
                    "badge_grouping_id": 3,
                    "system": true,
                    "long_description": "Ta odznaka jest przyznawana, gdy Twoja odpowiedź otrzyma 25 polubień. Twoja odpowiedź była wyjątkowa i uczyniła rozmowę o wiele bardziej interesującą.\n",
                    "slug": "dobra-odpowiedz",
                    "has_badge": false,
                    "manually_grantable": false,
                    "badge_type_id": 2
                },
                {
                    "id": 8,
                    "name": "Świetna odpowiedź",
                    "description": "Otrzymano 50 polubień w odpowiedzi",
                    "grant_count": 0,
                    "allow_title": false,
                    "multiple_grant": true,
                    "icon": "fa-certificate",
                    "image": null,
                    "listable": true,
                    "enabled": true,
                    "badge_grouping_id": 3,
                    "system": true,
                    "long_description": "Ta odznaka jest przyznawana, gdy Twoja odpowiedź otrzyma 50 polubień. Wow! Twoja odpowiedź była inspirująca, fascynująca, zabawna lub wnikliwa, a społeczność ją pokochała!\n",
                    "slug": "swietna-odpowiedz",
                    "has_badge": false,
                    "manually_grantable": false,
                    "badge_type_id": 1
                },
                {
                    "id": 18,
                    "name": "Niezły Temat",
                    "description": "Otrzymano 10 polubień w temacie.",
                    "grant_count": 0,
                    "allow_title": false,
                    "multiple_grant": true,
                    "icon": "fa-certificate",
                    "image": null,
                    "listable": true,
                    "enabled": true,
                    "badge_grouping_id": 3,
                    "system": true,
                    "long_description": "Ta odznaka jest przyznawana, gdy Twój temat uzyska 10 polubień. Rozpocząłeś interesującą rozmowę, która spodobała się społeczności.\n",
                    "slug": "niezly-temat",
                    "has_badge": false,
                    "manually_grantable": false,
                    "badge_type_id": 3
                },
                {
                    "id": 19,
                    "name": "Dobry Temat",
                    "description": "Otrzymano 25 polubień w temacie.",
                    "grant_count": 0,
                    "allow_title": false,
                    "multiple_grant": true,
                    "icon": "fa-certificate",
                    "image": null,
                    "listable": true,
                    "enabled": true,
                    "badge_grouping_id": 3,
                    "system": true,
                    "long_description": "Ta odznaka jest przyznawana, gdy Twój temat uzyska 25 polubień. Rozpocząłeś ożywioną rozmowę, wokół której zebrała się społeczność.\n",
                    "slug": "dobry-temat",
                    "has_badge": false,
                    "manually_grantable": false,
                    "badge_type_id": 2
                },
                {
                    "id": 20,
                    "name": "Świetny Temat",
                    "description": "Otrzymano 50 polubień w temacie.",
                    "grant_count": 0,
                    "allow_title": false,
                    "multiple_grant": true,
                    "icon": "fa-certificate",
                    "image": null,
                    "listable": true,
                    "enabled": true,
                    "badge_grouping_id": 3,
                    "system": true,
                    "long_description": "Ta odznaka jest przyznawana, gdy Twój temat uzyska 50 polubień. Rozpocząłeś fascynującą rozmowę, a społeczność pokochała ożywioną dyskusję, która zaowocowała w dobry temat!\n",
                    "slug": "swietny-temat",
                    "has_badge": false,
                    "manually_grantable": false,
                    "badge_type_id": 1
                },
                {
                    "id": 24,
                    "name": "Rocznica",
                    "description": "Aktywność przez rok, co najmniej jeden wpis",
                    "grant_count": 0,
                    "allow_title": false,
                    "multiple_grant": true,
                    "icon": "far-clock",
                    "image": null,
                    "listable": true,
                    "enabled": true,
                    "badge_grouping_id": 2,
                    "system": true,
                    "long_description": "Ta odznaka jest przyznawana, gdy jesteś członkiem od roku i masz co najmniej jeden post w tym roku. Dziękujemy za pozostawanie w pobliżu i wkład w naszą społeczność. Nie moglibyśmy tego zrobić bez Ciebie.\n",
                    "slug": "rocznica",
                    "has_badge": false,
                    "manually_grantable": false,
                    "badge_type_id": 2
                },
                {
                    "id": 28,
                    "name": "Popularny link",
                    "description": "Opublikowanie zewnętrznego linku, który otrzymał co najmniej 50 kliknięć",
                    "grant_count": 0,
                    "allow_title": false,
                    "multiple_grant": true,
                    "icon": "fa-certificate",
                    "image": null,
                    "listable": true,
                    "enabled": true,
                    "badge_grouping_id": 3,
                    "system": true,
                    "long_description": "Ta odznaka jest przyznawana, gdy link, który udostępniłeś zostanie otwarty przynajmniej 50 razy. Dziękujemy za dodawanie przydatnych linków, które mają wyraźny wkład w zawartość konwersacji!\n",
                    "slug": "popularny-link",
                    "has_badge": false,
                    "manually_grantable": false,
                    "badge_type_id": 3
                },
                {
                    "id": 29,
                    "name": "Gorący link",
                    "description": "Opublikowanie zewnętrznego linku, który otrzymał co najmniej 300 kliknięć",
                    "grant_count": 0,
                    "allow_title": false,
                    "multiple_grant": true,
                    "icon": "fa-certificate",
                    "image": null,
                    "listable": true,
                    "enabled": true,
                    "badge_grouping_id": 3,
                    "system": true,
                    "long_description": "Ta odznaka jest przyznawana, gdy link, który udostępniłeś zostanie otwarty przynajmniej 300 razy. Dziękujemy za udostępnienie ciekawe linku, który pozwolił rozwinąć konwersację i dodać nowy punkt widzenia dyskusji!\n",
                    "slug": "goracy-link",
                    "has_badge": false,
                    "manually_grantable": false,
                    "badge_type_id": 2
                },
                {
                    "id": 30,
                    "name": "Popularny link",
                    "description": "Opublikowanie zewnętrznego linku, który otrzymał co najmniej 1000 kliknięć",
                    "grant_count": 0,
                    "allow_title": false,
                    "multiple_grant": true,
                    "icon": "fa-certificate",
                    "image": null,
                    "listable": true,
                    "enabled": true,
                    "badge_grouping_id": 3,
                    "system": true,
                    "long_description": "Ta odznaka jest przyznawana, gdy link, który udostępniłeś zostanie otwarty przynajmniej 1000 razy. Wow! Udostępniłeś link, który wyraźnie przyczynił się do ulepszenia konwersacji poprzez dodanie niezbędnych szczegółów, zawartości i informacji. Dobra robota!\n",
                    "slug": "popularny-link",
                    "has_badge": false,
                    "manually_grantable": false,
                    "badge_type_id": 1
                },
                {
                    "id": 36,
                    "name": "Doceniony",
                    "description": "Otrzymano 1 polubienie w 20 wpisach",
                    "grant_count": 0,
                    "allow_title": false,
                    "multiple_grant": false,
                    "icon": "fa-heart",
                    "image": null,
                    "listable": true,
                    "enabled": true,
                    "badge_grouping_id": 2,
                    "system": true,
                    "long_description": "Ta odznaka jest przyznawana, gdy otrzymasz przynajmniej 20 polubień różnych wpisów. Społeczność lubi twój wkład do konwersacji!\n",
                    "slug": "doceniony",
                    "has_badge": false,
                    "manually_grantable": false,
                    "badge_type_id": 3
                },
                {
                    "id": 37,
                    "name": "Szanowany",
                    "description": "Otrzymano 2 polubienia w 100 wpisach",
                    "grant_count": 0,
                    "allow_title": false,
                    "multiple_grant": false,
                    "icon": "fa-heart",
                    "image": null,
                    "listable": true,
                    "enabled": true,
                    "badge_grouping_id": 2,
                    "system": true,
                    "long_description": "Ta odznaka jest przyznawana, gdy otrzymasz przynajmniej 2 polubienia na 100 różnych wpisach. Społeczność zaczyna szanować twój wkład do konwersacji.\n",
                    "slug": "szanowany",
                    "has_badge": false,
                    "manually_grantable": false,
                    "badge_type_id": 2
                },
                {
                    "id": 31,
                    "name": "Podziwiany",
                    "description": "Otrzymano 5 polubień w 300 wpisach",
                    "grant_count": 0,
                    "allow_title": false,
                    "multiple_grant": false,
                    "icon": "fa-heart",
                    "image": null,
                    "listable": true,
                    "enabled": true,
                    "badge_grouping_id": 2,
                    "system": true,
                    "long_description": "Ta odznaka jest przyznawana, gdy otrzymasz przynajmniej 5 polubień na 300 różnych wpisach. Wow! Społeczność docenia twój częsty i wysokiej jakości wkład w konwersacje.\n",
                    "slug": "podziwiany",
                    "has_badge": false,
                    "manually_grantable": false,
                    "badge_type_id": 1
                },
                {
                    "id": 38,
                    "name": "Dziękuje",
                    "description": "Ma 20 polubionych wpisów i dał 10 polubień",
                    "grant_count": 0,
                    "allow_title": false,
                    "multiple_grant": false,
                    "icon": "fa-heart",
                    "image": null,
                    "listable": true,
                    "enabled": true,
                    "badge_grouping_id": 2,
                    "system": true,
                    "long_description": "Ta odznaka jest przyznawana, gdy masz co najmniej 20 polubionych wpisów i dałeś w zamian 10 lub więcej polubień. Gdy ktoś polubi twój wpis, znajdź czas, by polubić również wpisy innych użytkowników.\n",
                    "slug": "dziekuje",
                    "has_badge": false,
                    "manually_grantable": false,
                    "badge_type_id": 3
                },
                {
                    "id": 32,
                    "name": "Oddać",
                    "description": "Ma 100 polubionych wpisów i dał 100 polubień",
                    "grant_count": 0,
                    "allow_title": false,
                    "multiple_grant": false,
                    "icon": "fa-heart",
                    "image": null,
                    "listable": true,
                    "enabled": true,
                    "badge_grouping_id": 2,
                    "system": true,
                    "long_description": "Ta odznaka jest przyznawana, gdy masz co najmniej 100 polubionych wpisów i dałeś w zamian 100 lub więcej polubień. Dziękujemy za twoją aktywność!\n",
                    "slug": "oddac",
                    "has_badge": false,
                    "manually_grantable": false,
                    "badge_type_id": 2
                },
                {
                    "id": 39,
                    "name": "Empatyczny",
                    "description": "Ma 500 polubionych wpisów i dał 1000 polubień",
                    "grant_count": 0,
                    "allow_title": false,
                    "multiple_grant": false,
                    "icon": "fa-heart",
                    "image": null,
                    "listable": true,
                    "enabled": true,
                    "badge_grouping_id": 2,
                    "system": true,
                    "long_description": "Ta odznaka jest przyznawana, gdy posiadasz 500 polubionych postów i oddałeś 1000 lub więcej polubień w zamian. Wow! Jesteś wzorem hojności i wzajemnego uznania :two_hearts:.\n",
                    "slug": "empatyczny",
                    "has_badge": false,
                    "manually_grantable": false,
                    "badge_type_id": 1
                },
                {
                    "id": 33,
                    "name": "Z miłości",
                    "description": "Wykorzystano 50 polubień w ciągu dnia",
                    "grant_count": 0,
                    "allow_title": false,
                    "multiple_grant": false,
                    "icon": "fa-heart",
                    "image": null,
                    "listable": true,
                    "enabled": true,
                    "badge_grouping_id": 2,
                    "system": true,
                    "long_description": "Ta odznaka jest przyznawana, gdy wykorzystasz wszystkie 50 swoich codziennych polubień. Pamiętając o tym, aby poświęcić chwilę i polubić posty, które lubisz i cenisz, zachęcasz innych członków społeczności do tworzenia jeszcze lepszych dyskusji w przyszłości.\n",
                    "slug": "z-milosci",
                    "has_badge": false,
                    "manually_grantable": false,
                    "badge_type_id": 3
                },
                {
                    "id": 34,
                    "name": "Wyższa miłość",
                    "description": "Użyto 50 polubień w ciągu dnia 5 razy",
                    "grant_count": 0,
                    "allow_title": false,
                    "multiple_grant": false,
                    "icon": "fa-heart",
                    "image": null,
                    "listable": true,
                    "enabled": true,
                    "badge_grouping_id": 2,
                    "system": true,
                    "long_description": "Ta odznaka jest przyznawana, gdy wykorzystasz wszystkie 50 swoich codziennych polubień przez 5 dni. Dziękujemy za poświęcenie czasu na aktywne zachęcanie użytkowników do nowych rozmów każdego dnia!\n",
                    "slug": "wyzsza-milosc",
                    "has_badge": false,
                    "manually_grantable": false,
                    "badge_type_id": 2
                },
                {
                    "id": 35,
                    "name": "Szaleńczo zakochany",
                    "description": "Użyto 50 polubień w ciągu dnia 20 razy",
                    "grant_count": 0,
                    "allow_title": false,
                    "multiple_grant": false,
                    "icon": "fa-heart",
                    "image": null,
                    "listable": true,
                    "enabled": true,
                    "badge_grouping_id": 2,
                    "system": true,
                    "long_description": "Ta odznaka jest przyznawana, gdy wykorzystasz wszystkie 50 swoich codziennych polubień przez 20 dni. Wow! Jesteś wzorem do naśladowania, jeśli chodzi o zachęcanie do dyskusji innych członków naszej społeczności!\n",
                    "slug": "szalenczo-zakochany",
                    "has_badge": false,
                    "manually_grantable": false,
                    "badge_type_id": 1
                },
                {
                    "id": 42,
                    "name": "Pierwszy Onebox",
                    "description": "Dodany link został poddany funkcji oneboxe",
                    "grant_count": 0,
                    "allow_title": false,
                    "multiple_grant": false,
                    "icon": "fa-certificate",
                    "image": null,
                    "listable": true,
                    "enabled": true,
                    "badge_grouping_id": 1,
                    "system": true,
                    "long_description": "Ta odznaka jest przyznawana za pierwszym razem, gdy publikujesz link w osobnym wierszu, który automatycznie rozwija się w ramkę z podsumowaniem, tytułem i (jeśli jest dostępne) zdjęciem.\n",
                    "slug": "pierwszy-onebox",
                    "has_badge": false,
                    "manually_grantable": false,
                    "badge_type_id": 3
                },
                {
                    "id": 43,
                    "name": "Pierwsza Odpowiedz przez Email",
                    "description": "Odpowiedział na wpis poprzez email",
                    "grant_count": 0,
                    "allow_title": false,
                    "multiple_grant": false,
                    "icon": "fa-certificate",
                    "image": null,
                    "listable": true,
                    "enabled": true,
                    "badge_grouping_id": 1,
                    "system": true,
                    "long_description": "Ta odznaka jest przyznawana kiedy pierwszy raz odpowiesz na wpis poprzez maila:.\n",
                    "slug": "pierwsza-odpowiedz-przez-email",
                    "has_badge": false,
                    "manually_grantable": false,
                    "badge_type_id": 3
                },
                {
                    "id": 45,
                    "name": "Entuzjasta",
                    "description": "Odwiedziono 10 kolejnych dni",
                    "grant_count": 0,
                    "allow_title": false,
                    "multiple_grant": false,
                    "icon": "far-eye",
                    "image": null,
                    "listable": true,
                    "enabled": true,
                    "badge_grouping_id": 2,
                    "system": true,
                    "long_description": "Ta odznaka jest przydzielana za odwiedzanie 10 dni pod rząd.\nDziękujemy za bycie z nami przez ponad tydzień!\n",
                    "slug": "entuzjasta",
                    "has_badge": false,
                    "manually_grantable": false,
                    "badge_type_id": 3
                },
                {
                    "id": 41,
                    "name": "Pierwszy Emoji",
                    "description": "Użyto Emoji we Wpisie",
                    "grant_count": 1,
                    "allow_title": false,
                    "multiple_grant": false,
                    "icon": "fa-certificate",
                    "image": null,
                    "listable": true,
                    "enabled": true,
                    "badge_grouping_id": 1,
                    "system": true,
                    "long_description": "Ta odznaka jest przyznawana za pierwszym razem, gdy dodasz emotikon do swojego posta :thumbsup:. Emotikony pozwalają wyrazić emocje w swoich wypowiedziach, od szczęścia :smiley: przez smutek :anguished: po złość :angry: i wszystko pomiędzy :sunglasses:. Po prostu wpisz : (dwukropek) lub naciśnij przycisk paska narzędzi Emoji w edytorze, aby wybrać spośród setek opcji do wyboru :ok_hand:\n",
                    "slug": "pierwszy-emoji",
                    "has_badge": false,
                    "manually_grantable": false,
                    "badge_type_id": 3
                },
                {
                    "id": 44,
                    "name": "Nowy Użytkownik Miesiąca",
                    "description": "Wybitny wkład w pierwszym miesiącu",
                    "grant_count": 1,
                    "allow_title": false,
                    "multiple_grant": false,
                    "icon": "fa-certificate",
                    "image": null,
                    "listable": true,
                    "enabled": true,
                    "badge_grouping_id": 1,
                    "system": true,
                    "long_description": "Ta odznaka jest przyznawana, aby pogratulować dwóm użytkownikom każdego miesiąca za ich wkład w rozwój; mierzone na podstawie tego jak często ich wpisy dostawały polubienia i przez kogo.\n",
                    "slug": "nowy-uzytkownik-miesiaca",
                    "has_badge": false,
                    "manually_grantable": false,
                    "badge_type_id": 3
                },
                {
                    "id": 46,
                    "name": "Miłośnik",
                    "description": "Odwiedziono 100 kolejnych dni",
                    "grant_count": 0,
                    "allow_title": false,
                    "multiple_grant": false,
                    "icon": "far-eye",
                    "image": null,
                    "listable": true,
                    "enabled": true,
                    "badge_grouping_id": 2,
                    "system": true,
                    "long_description": "Ta odznaka jest przyznawana za odwiedzanie forum przez 100 kolejnych dni. To więcej niż trzy miesiące!\n",
                    "slug": "milosnik",
                    "has_badge": false,
                    "manually_grantable": false,
                    "badge_type_id": 2
                },
                {
                    "id": 47,
                    "name": "Wielbiciel",
                    "description": "Odwiedziono 365 kolejnych dni",
                    "grant_count": 0,
                    "allow_title": false,
                    "multiple_grant": false,
                    "icon": "far-eye",
                    "image": null,
                    "listable": true,
                    "enabled": true,
                    "badge_grouping_id": 2,
                    "system": true,
                    "long_description": "Ta odznaka jest przyznawana za odwiedzanie forum przez 365 kolejnych dni. Wow, to cały rok!\n",
                    "slug": "wielbiciel",
                    "has_badge": false,
                    "manually_grantable": false,
                    "badge_type_id": 1
                },
                {
                    "id": 100,
                    "name": "Certyfikowany",
                    "description": "Ukończono tutorial dla nowych użytkowników",
                    "grant_count": 0,
                    "allow_title": false,
                    "multiple_grant": false,
                    "icon": "fa-certificate",
                    "image": null,
                    "listable": true,
                    "enabled": true,
                    "badge_grouping_id": 1,
                    "system": true,
                    "long_description": "Odznaka została nadana za ukończenie interaktywnego tutorialu dla nowych użytkowników. Poznałeś podstawowe narzędzia dyskusji i jesteś teraz certyfikowany!\n",
                    "slug": "certyfikowany",
                    "has_badge": false,
                    "manually_grantable": false,
                    "badge_type_id": 3
                },
                {
                    "id": 101,
                    "name": "Licencjonowany",
                    "description": "Ukończono tutorial dla zaawansowanych użytkowników",
                    "grant_count": 0,
                    "allow_title": false,
                    "multiple_grant": false,
                    "icon": "fa-certificate",
                    "image": null,
                    "listable": true,
                    "enabled": true,
                    "badge_grouping_id": 1,
                    "system": true,
                    "long_description": "Odznaka została nadana za ukończenie interaktywnego tutorialu dla zaawansowanych użytkowników. Poznałeś zaawansowane narzędzia dyskusji i jesteś teraz w pełni licencjonowany!\n",
                    "slug": "licencjonowany",
                    "has_badge": false,
                    "manually_grantable": false,
                    "badge_type_id": 2
                },
                {
                    "id": 40,
                    "name": "Pierwsze Wspomnienie",
                    "description": "Wspomniano o użytkowniku we wpisie",
                    "grant_count": 1,
                    "allow_title": false,
                    "multiple_grant": false,
                    "icon": "fa-certificate",
                    "image": null,
                    "listable": true,
                    "enabled": true,
                    "badge_grouping_id": 1,
                    "system": true,
                    "long_description": "Ta plakietka jest przyznawana, gdy po raz pierwszy wspomnisz czyjąś @nazwę użytkownika w swoim poście. Każda wzmianka generuje powiadomienie do tej osoby, aby ta wiedziała o Twoim poście. Po prostu zacznij wpisywać @ (w symbolu), aby wspomnieć o dowolnym użytkowniku lub, jeśli jest to dozwolone, grupie - jest to wygodny sposób zwrócenia uwagi.\n",
                    "slug": "pierwsze-wspomnienie",
                    "has_badge": false,
                    "manually_grantable": false,
                    "badge_type_id": 3
                },
                {
                    "id": 15,
                    "name": "Pierwszy cytat",
                    "description": "Zacytowano wpis",
                    "grant_count": 0,
                    "allow_title": false,
                    "multiple_grant": false,
                    "icon": "fa-certificate",
                    "image": null,
                    "listable": true,
                    "enabled": true,
                    "badge_grouping_id": 1,
                    "system": true,
                    "long_description": "Ta odznaka jest przyznawana, gdy po raz pierwszy zacytujesz post w swojej odpowiedzi. Cytowanie w odpowiedzi odpowiednich fragmentów wcześniejszych postów pomaga utrzymać dyskusję na temat. Najłatwiejszym sposobem cytowania jest zaznaczenie fragmentu wpisu, a następnie naciśnięcie dowolnego przycisku odpowiedzi. Cytuj hojnie!\n",
                    "slug": "pierwszy-cytat",
                    "has_badge": false,
                    "manually_grantable": false,
                    "badge_type_id": 3
                },
                {
                    "id": 1,
                    "name": "Podstawowy",
                    "description": "<a href=\"https://blog.discourse.org/2018/06/understanding-discourse-trust-levels/\">Otrzymano</a> wszystkie niezbędne funkcje społeczności.",
                    "grant_count": 4,
                    "allow_title": false,
                    "multiple_grant": false,
                    "icon": "fa-user",
                    "image": null,
                    "listable": true,
                    "enabled": true,
                    "badge_grouping_id": 4,
                    "system": true,
                    "long_description": "Ta odznaka jest przyznawana za zdobycie 1. poziomu zaufania. Dziękujemy, że jesteś z nami i czytasz różne tematy, aby poznać naszą społeczność. Ograniczenia nałożone na Ciebie jako na nowego użytkownika / nową użytkowniczkę zostały zniesione i otrzymujesz dostęp do wszystkich niezbędnych funkcji społecznościowych, takich jak wysyłanie wiadomości prywatnych, flagowanie wpisów, edytowanie wiki czy możliwość dodawania wielu obrazków i linków we wpisach.\n",
                    "slug": "podstawowy",
                    "has_badge": true,
                    "manually_grantable": false,
                    "badge_type_id": 3
                }
            ]
        };

        return of(badgesResponse.badges);
    }

    /**
     * Updates badges
     * @param {ForumBadge[]} badges 
     * @returns {ForumBadge[]}
     */
    private updateBadges(badges: ForumBadge[]): ForumBadge[] {
        return badges.map(badge => {
            const iconArray = badge.icon.split('-');
            iconArray[0] = 'fa';

            return {
                ...badge,
                fa_icon: StringHelper.toCamelCase(iconArray.join('-')),
            };
        }).sort((a, b) => (a.id > b.id) ? 0 : -1);
    }

    /**
     * Gets notifications
     * @returns {Observable<ForumNotification[]>} notifications 
     */
    getNotifications(): Observable<ForumNotification[]> {
        // https://forum.szkolenia.dane.gov.pl/notifications.json?username=kamil&filter=read
        const forumNotificationsResponse = {
            "notifications": [
                {
                    "id": 40,
                    "user_id": 3,
                    "notification_type": 2,
                    "read": true,
                    "created_at": "2021-02-12T07:42:11.292Z",
                    "post_number": 4,
                    "topic_id": 18,
                    "fancy_title": "Temat musi zawierać 15 znaków",
                    "slug": "temat-musi-zawierac-15-znakow",
                    "data": {
                        "topic_title": "Temat musi zawierać 15 znaków",
                        "original_post_id": 41,
                        "original_post_type": 1,
                        "original_username": "user",
                        "revision_number": null,
                        "display_username": "user"
                    }
                },
                {
                    "id": 37,
                    "user_id": 3,
                    "notification_type": 6,
                    "read": true,
                    "created_at": "2021-02-04T13:50:53.475Z",
                    "post_number": 1,
                    "topic_id": 22,
                    "fancy_title": "Jesteś nowym użytkownikiem miesiąca!",
                    "slug": "jestes-nowym-uzytkownikiem-miesiaca",
                    "data": {
                        "topic_title": "Jesteś nowym użytkownikiem miesiąca!",
                        "original_post_id": 38,
                        "original_post_type": 1,
                        "original_username": "system",
                        "revision_number": null,
                        "display_username": "system"
                    }
                },
                {
                    "id": 34,
                    "user_id": 3,
                    "notification_type": 12,
                    "read": true,
                    "created_at": "2021-01-28T19:54:04.592Z",
                    "post_number": null,
                    "topic_id": null,
                    "slug": null,
                    "data": {
                        "badge_id": 11,
                        "badge_name": "Pierwsze polubienie",
                        "badge_slug": "pierwsze-polubienie",
                        "badge_title": false,
                        "username": "kamil"
                    }
                },
                {
                    "id": 31,
                    "user_id": 3,
                    "notification_type": 12,
                    "read": true,
                    "created_at": "2021-01-21T14:31:09.496Z",
                    "post_number": null,
                    "topic_id": null,
                    "slug": null,
                    "data": {
                        "badge_id": 5,
                        "badge_name": "Powitanie",
                        "badge_slug": "powitanie",
                        "badge_title": false,
                        "username": "kamil"
                    }
                },
                {
                    "id": 23,
                    "user_id": 3,
                    "notification_type": 12,
                    "read": true,
                    "created_at": "2021-01-20T06:49:22.073Z",
                    "post_number": null,
                    "topic_id": null,
                    "slug": null,
                    "data": {
                        "badge_id": 1,
                        "badge_name": "Podstawowy",
                        "badge_slug": "podstawowy",
                        "badge_title": false,
                        "username": "kamil"
                    }
                },
                {
                    "id": 11,
                    "user_id": 3,
                    "notification_type": 12,
                    "read": true,
                    "created_at": "2021-01-19T11:49:12.166Z",
                    "post_number": null,
                    "topic_id": null,
                    "slug": null,
                    "data": {
                        "badge_id": 40,
                        "badge_name": "Pierwsze Wspomnienie",
                        "badge_slug": "pierwsze-wspomnienie",
                        "badge_title": false,
                        "username": "kamil"
                    }
                },
                {
                    "id": 9,
                    "user_id": 3,
                    "notification_type": 12,
                    "read": true,
                    "created_at": "2021-01-19T11:46:13.853Z",
                    "post_number": null,
                    "topic_id": null,
                    "slug": null,
                    "data": {
                        "badge_id": 14,
                        "badge_name": "Pierwszy link",
                        "badge_slug": "pierwszy-link",
                        "badge_title": false,
                        "username": "kamil"
                    }
                }
            ],
            "total_rows_notifications": 7,
            "seen_notification_id": 40,
            "load_more_notifications": "/notifications?filter=read&offset=60&username=kamil"
        }

        return of(forumNotificationsResponse.notifications as ForumNotification[]);
    }

    /**
     * Gets notifications with badges
     * @returns {Observable<ForumNotificationWithBadge[]>} notifications with badges 
     */
    getNotificationsWithBadges(): Observable<ForumNotificationWithBadge[]> {
        return combineLatest([this.getBadges(), this.getNotifications()]).pipe(
            map(([badges, notifications]) => {
                const updatedBadges = this.updateBadges(badges);

                return notifications.map(notification => {
                    const badgeId = notification.data?.badge_id ? notification.data?.badge_id : notification.notification_type;
                    
                    return {
                        ...notification,
                        badge: updatedBadges.find(badge => badge.id === badgeId)
                    }
                });
            })
        );
    }

    /**
     * Gets categories
     * @returns {Observable<ForumCategory[]>} categories 
     */
    getCategories(): Observable<ForumCategory[]> {
        // https://forum.szkolenia.dane.gov.pl/categories.json
        const categoriesResponse = {
            "category_list": {
                "can_create_category": true,
                "can_create_topic": true,
                "draft": null,
                "draft_key": "new_topic",
                "draft_sequence": 19,
                "categories": [
                    {
                        "id": 6,
                        "name": "Zbiory danych",
                        "color": "0088CC",
                        "text_color": "FFFFFF",
                        "slug": "zbiory-danych",
                        "topic_count": 2,
                        "post_count": 5,
                        "position": 4,
                        "description": null,
                        "description_text": null,
                        "description_excerpt": null,
                        "topic_url": "/t/o-kategorii-zbiory-danych/14",
                        "read_restricted": false,
                        "permission": 1,
                        "notification_level": 1,
                        "can_edit": true,
                        "topic_template": null,
                        "has_children": false,
                        "sort_order": null,
                        "sort_ascending": null,
                        "show_subcategory_list": false,
                        "num_featured_topics": 3,
                        "default_view": null,
                        "subcategory_list_style": "rows_with_featured_topics",
                        "default_top_period": "all",
                        "default_list_filter": "all",
                        "minimum_required_tags": 0,
                        "navigate_to_first_post_after_read": false,
                        "topics_day": 0,
                        "topics_week": 0,
                        "topics_month": 2,
                        "topics_year": 2,
                        "topics_all_time": 2,
                        "uploaded_logo": null,
                        "uploaded_background": null
                    },
                    {
                        "id": 3,
                        "name": "Zespół",
                        "color": "E45735",
                        "text_color": "FFFFFF",
                        "slug": "zespol",
                        "topic_count": 5,
                        "post_count": 18,
                        "position": 2,
                        "description": "Ukryta kategoria dla rozmów zespołu. Tematy są widoczne tylko dla adminów i moderatorów.",
                        "description_text": "Ukryta kategoria dla rozmów zespołu. Tematy są widoczne tylko dla adminów i moderatorów.",
                        "description_excerpt": "Ukryta kategoria dla rozmów zespołu. Tematy są widoczne tylko dla adminów i moderatorów.",
                        "topic_url": "/t/o-kategorii-zespol/2",
                        "read_restricted": true,
                        "permission": 1,
                        "notification_level": 1,
                        "can_edit": true,
                        "topic_template": null,
                        "has_children": false,
                        "sort_order": null,
                        "sort_ascending": null,
                        "show_subcategory_list": false,
                        "num_featured_topics": 3,
                        "default_view": null,
                        "subcategory_list_style": "rows_with_featured_topics",
                        "default_top_period": "all",
                        "default_list_filter": "all",
                        "minimum_required_tags": 0,
                        "navigate_to_first_post_after_read": false,
                        "topics_day": 0,
                        "topics_week": 0,
                        "topics_month": 0,
                        "topics_year": 5,
                        "topics_all_time": 5,
                        "uploaded_logo": null,
                        "uploaded_background": null
                    },
                    {
                        "id": 5,
                        "name": "Instrukcje i porady",
                        "color": "3AB54A",
                        "text_color": "FFFFFF",
                        "slug": "instrukcje-porady",
                        "topic_count": 1,
                        "post_count": 1,
                        "position": 4,
                        "description": "Litwo! Ojczyzno moja! Ty jesteś jak zdrowie. Ile cię trzeba cenić, ten zaszczyt należy. Idąc z powozu. konie rżące lecą ze świecami w tylu szlachty, w węzełki mało w domu Sędziego mrugał. widać z boku sąsiadki a twarz spójrzała, z pierwszej lękliwości całkiem już zjechał z dom i jąkał się i każdy po kryjomu kazał stoły z rozsądkiem wiedział, czy młodzież czekają. Pójdziemy, jeśli nasza młodzie wyjeżdża za zającami nie skąpił. On mnie to mówiąc, że odbite od siebie mimowolnie porządku i westchnień, i tylko są łąki i po świeci jeździ wenecki diabeł w Ostrej świecisz Bramie! Ty, co wzdłuż po łące ucichły i tuż za duszę utęsknioną do zdrowia powróciłaś cudem na parkanie stała wypisana i pijąc obie Tadeusz przyglądał się cukier wytapia i każdego wodza legijonu i z wolna w tabakierkę złotą na dzień za stołem. Z góry już robił projekt, że tak zawsze służy której lat kilku młodych od puszcz libijskich latał do bębna tęsknił, siedząc w kielni siedziały dwa susy psy tuż, i swój rydwan orły złote obok srebrnych, od mężczyzn i jak biały ptak zleciała.",
                        "description_text": "Litwo! Ojczyzno moja! Ty jesteś jak zdrowie. Ile cię trzeba cenić, ten zaszczyt należy. Idąc z powozu. konie rżące lecą ze świecami w tylu szlachty, w węzełki mało w domu Sędziego mrugał. widać z boku sąsiadki a twarz spójrzała, z pierwszej lękliwości całkiem już zjechał z dom i jąkał się i każdy po kryjomu kazał stoły z rozsądkiem wiedział, czy młodzież czekają. Pójdziemy, jeśli nasza młodzie wyjeżdża za zającami nie skąpił. On mnie to mówiąc, że odbite od siebie mimowolnie porządku i westchnień, i tylko są łąki i po świeci jeździ wenecki diabeł w Ostrej świecisz Bramie! Ty, co wzdłuż po łące ucichły i tuż za duszę utęsknioną do zdrowia powróciłaś cudem na parkanie stała wypisana i pijąc obie Tadeusz przyglądał się cukier wytapia i każdego wodza legijonu i z wolna w tabakierkę złotą na dzień za stołem. Z góry już robił projekt, że tak zawsze służy której lat kilku młodych od puszcz libijskich latał do bębna tęsknił, siedząc w kielni siedziały dwa susy psy tuż, i swój rydwan orły złote obok srebrnych, od mężczyzn i jak biały ptak zleciała.",
                        "description_excerpt": "Litwo! Ojczyzno moja! Ty jesteś jak zdrowie. Ile cię trzeba cenić, ten zaszczyt należy. Idąc z powozu. konie rżące lecą ze świecami w tylu szlachty, w węzełki mało w domu Sędziego mrugał. widać z boku sąsiadki a twarz spójrzała, z pierwszej lękliwości całkiem już zjechał z dom i jąkał się i każdy po&hellip;",
                        "topic_url": "/t/o-kategorii-instrukcje-i-porady/12",
                        "read_restricted": false,
                        "permission": 1,
                        "notification_level": 1,
                        "can_edit": true,
                        "topic_template": null,
                        "has_children": false,
                        "sort_order": null,
                        "sort_ascending": null,
                        "show_subcategory_list": false,
                        "num_featured_topics": 3,
                        "default_view": null,
                        "subcategory_list_style": "rows_with_featured_topics",
                        "default_top_period": "all",
                        "default_list_filter": "all",
                        "minimum_required_tags": 0,
                        "navigate_to_first_post_after_read": false,
                        "topics_day": 0,
                        "topics_week": 0,
                        "topics_month": 0,
                        "topics_year": 1,
                        "topics_all_time": 1,
                        "uploaded_logo": null,
                        "uploaded_background": null
                    },
                    {
                        "id": 1,
                        "name": "Bez kategorii",
                        "color": "0088CC",
                        "text_color": "FFFFFF",
                        "slug": "bez-kategorii",
                        "topic_count": 2,
                        "post_count": 2,
                        "position": 0,
                        "description": "Tematy które nie potrzebują kategorii, albo nie nadają się do żadnej innej.",
                        "description_text": "Tematy które nie potrzebują kategorii, albo nie nadają się do żadnej innej.",
                        "description_excerpt": "Tematy które nie potrzebują kategorii, albo nie nadają się do żadnej innej.",
                        "topic_url": null,
                        "read_restricted": false,
                        "permission": 1,
                        "notification_level": 1,
                        "can_edit": true,
                        "topic_template": null,
                        "has_children": false,
                        "sort_order": null,
                        "sort_ascending": null,
                        "show_subcategory_list": false,
                        "num_featured_topics": 3,
                        "default_view": null,
                        "subcategory_list_style": "rows_with_featured_topics",
                        "default_top_period": "all",
                        "default_list_filter": "all",
                        "minimum_required_tags": 0,
                        "navigate_to_first_post_after_read": false,
                        "topics_day": 0,
                        "topics_week": 0,
                        "topics_month": 0,
                        "topics_year": 2,
                        "topics_all_time": 2,
                        "is_uncategorized": true,
                        "uploaded_logo": null,
                        "uploaded_background": null
                    },
                    {
                        "id": 2,
                        "name": "Dyskusje o portalu dane.gov.pl",
                        "color": "808281",
                        "text_color": "FFFFFF",
                        "slug": "dyskusje-o-portalu",
                        "topic_count": 0,
                        "post_count": 0,
                        "position": 1,
                        "description": "Dyskusje o tej stronie, jej organizacji, tym jak działa i jak możemy ją usprawnić.",
                        "description_text": "Dyskusje o tej stronie, jej organizacji, tym jak działa i jak możemy ją usprawnić.",
                        "description_excerpt": "Dyskusje o tej stronie, jej organizacji, tym jak działa i jak możemy ją usprawnić.",
                        "topic_url": "/t/o-kategorii-dyskusje-o-portalu-dane-gov-pl/1",
                        "read_restricted": false,
                        "permission": 1,
                        "notification_level": 1,
                        "can_edit": true,
                        "topic_template": "",
                        "has_children": false,
                        "sort_order": "",
                        "sort_ascending": null,
                        "show_subcategory_list": false,
                        "num_featured_topics": 3,
                        "default_view": "",
                        "subcategory_list_style": "rows_with_featured_topics",
                        "default_top_period": "all",
                        "default_list_filter": "all",
                        "minimum_required_tags": 0,
                        "navigate_to_first_post_after_read": false,
                        "topics_day": 0,
                        "topics_week": 0,
                        "topics_month": 0,
                        "topics_year": 0,
                        "topics_all_time": 0,
                        "uploaded_logo": null,
                        "uploaded_background": null
                    }
                ]
            }
        }

        return of(categoriesResponse.category_list.categories);
    }

    /**
     * Gets latest topics
     * @param {number} [offset] 
     * @returns {Observable<ForumTopic[]>} lates topics
     */
    getLatestTopics(offset = 3): Observable<ForumTopic[]> {
        // https://forum.szkolenia.dane.gov.pl/latest.json
        const latestTopicsResponse = {
            "users": [
                {
                    "id": 3,
                    "username": "kamil",
                    "name": "kamil.suchodol",
                    "avatar_template": "/letter_avatar_proxy/v4/letter/k/94ad74/{size}.png"
                },
                {
                    "id": 1,
                    "username": "user",
                    "name": "user",
                    "avatar_template": "/user_avatar/forum.szkolenia.dane.gov.pl/user/{size}/8_2.png"
                },
                {
                    "id": 4,
                    "username": "focus180",
                    "name": null,
                    "avatar_template": "/letter_avatar_proxy/v4/letter/f/df705f/{size}.png"
                },
                {
                    "id": 2,
                    "username": "macgra",
                    "name": "",
                    "avatar_template": "/letter_avatar_proxy/v4/letter/m/90ced4/{size}.png"
                },
                {
                    "id": -1,
                    "username": "system",
                    "name": "system",
                    "avatar_template": "/user_avatar/forum.szkolenia.dane.gov.pl/system/{size}/1_2.png"
                }
            ],
            "primary_groups": [],
            "topic_list": {
                "can_create_topic": true,
                "draft": null,
                "draft_key": "new_topic",
                "draft_sequence": 19,
                "per_page": 30,
                "topics": [
                    {
                        "id": 18,
                        "title": "Temat musi zawierać 15 znaków",
                        "fancy_title": "Temat musi zawierać 15 znaków",
                        "slug": "temat-musi-zawierac-15-znakow",
                        "posts_count": 4,
                        "reply_count": 1,
                        "highest_post_number": 4,
                        "image_url": null,
                        "created_at": "2021-01-19T11:45:57.107Z",
                        "last_posted_at": "2021-02-12T07:42:10.700Z",
                        "bumped": true,
                        "bumped_at": "2021-02-12T07:42:10.700Z",
                        "archetype": "regular",
                        "unseen": false,
                        "last_read_post_number": 4,
                        "unread": 0,
                        "new_posts": 0,
                        "pinned": false,
                        "unpinned": null,
                        "visible": true,
                        "closed": false,
                        "archived": false,
                        "notification_level": 2,
                        "bookmarked": false,
                        "liked": false,
                        "views": 16,
                        "like_count": 0,
                        "has_summary": false,
                        "last_poster_username": "user",
                        "category_id": 6,
                        "pinned_globally": false,
                        "featured_link": null,
                        "posters": [
                            {
                                "extras": null,
                                "description": "Autor pierwszego wpisu",
                                "user_id": 3,
                                "primary_group_id": null
                            },
                            {
                                "extras": "latest",
                                "description": "Autor najnowszego wpisu",
                                "user_id": 1,
                                "primary_group_id": null
                            }
                        ]
                    },
                    {
                        "id": 21,
                        "title": "Porozmawiajmy o nowych tematach na forum",
                        "fancy_title": "Porozmawiajmy o nowych tematach na forum",
                        "slug": "porozmawiajmy-o-nowych-tematach-na-forum",
                        "posts_count": 1,
                        "reply_count": 0,
                        "highest_post_number": 1,
                        "image_url": null,
                        "created_at": "2021-02-04T08:58:01.557Z",
                        "last_posted_at": "2021-02-04T08:58:01.849Z",
                        "bumped": true,
                        "bumped_at": "2021-02-04T08:58:01.849Z",
                        "archetype": "regular",
                        "unseen": false,
                        "last_read_post_number": 1,
                        "unread": 0,
                        "new_posts": 0,
                        "pinned": false,
                        "unpinned": null,
                        "visible": true,
                        "closed": false,
                        "archived": false,
                        "notification_level": 2,
                        "bookmarked": false,
                        "liked": false,
                        "views": 8,
                        "like_count": 0,
                        "has_summary": false,
                        "last_poster_username": "user",
                        "category_id": 6,
                        "pinned_globally": false,
                        "featured_link": null,
                        "posters": [
                            {
                                "extras": "latest single",
                                "description": "Autor pierwszego wpisu, Autor najnowszego wpisu",
                                "user_id": 1,
                                "primary_group_id": null
                            }
                        ]
                    },
                    {
                        "id": 15,
                        "title": "Lista beneficjentów (projektów) Funduszy Europejskich 2014-2020",
                        "fancy_title": "Lista beneficjentów (projektów) Funduszy Europejskich 2014-2020",
                        "slug": "lista-beneficjentow-projektow-funduszy-europejskich-2014-2020",
                        "posts_count": 11,
                        "reply_count": 6,
                        "highest_post_number": 12,
                        "image_url": null,
                        "created_at": "2020-12-07T07:42:03.317Z",
                        "last_posted_at": "2021-01-27T17:36:19.308Z",
                        "bumped": true,
                        "bumped_at": "2021-01-21T14:30:29.847Z",
                        "archetype": "regular",
                        "unseen": false,
                        "last_read_post_number": 12,
                        "unread": 0,
                        "new_posts": 0,
                        "pinned": false,
                        "unpinned": true,
                        "visible": true,
                        "closed": false,
                        "archived": false,
                        "notification_level": 2,
                        "bookmarked": false,
                        "liked": true,
                        "views": 27,
                        "like_count": 6,
                        "has_summary": false,
                        "last_poster_username": "user",
                        "category_id": 3,
                        "pinned_globally": false,
                        "featured_link": null,
                        "posters": [
                            {
                                "extras": "latest",
                                "description": "Autor pierwszego wpisu, Autor najnowszego wpisu",
                                "user_id": 1,
                                "primary_group_id": null
                            },
                            {
                                "extras": null,
                                "description": "Aktywny uczestnik",
                                "user_id": 3,
                                "primary_group_id": null
                            },
                            {
                                "extras": null,
                                "description": "Aktywny uczestnik",
                                "user_id": 4,
                                "primary_group_id": null
                            },
                            {
                                "extras": null,
                                "description": "Aktywny uczestnik",
                                "user_id": 2,
                                "primary_group_id": null
                            }
                        ]
                    },
                    {
                        "id": 13,
                        "title": "Jak dobrze przygotować dane typu tabelarycznego?",
                        "fancy_title": "Jak dobrze przygotować dane typu tabelarycznego?",
                        "slug": "jak-dobrze-przygotowac-dane-typu-tabelarycznego",
                        "posts_count": 1,
                        "reply_count": 0,
                        "highest_post_number": 1,
                        "image_url": null,
                        "created_at": "2020-12-07T07:33:33.501Z",
                        "last_posted_at": "2020-12-07T07:33:33.593Z",
                        "bumped": true,
                        "bumped_at": "2020-12-07T07:33:33.593Z",
                        "archetype": "regular",
                        "unseen": false,
                        "last_read_post_number": 1,
                        "unread": 0,
                        "new_posts": 0,
                        "pinned": false,
                        "unpinned": null,
                        "visible": true,
                        "closed": false,
                        "archived": false,
                        "notification_level": 3,
                        "bookmarked": false,
                        "liked": false,
                        "views": 9,
                        "like_count": 0,
                        "has_summary": false,
                        "last_poster_username": "user",
                        "category_id": 5,
                        "pinned_globally": false,
                        "featured_link": null,
                        "posters": [
                            {
                                "extras": "latest single",
                                "description": "Autor pierwszego wpisu, Autor najnowszego wpisu",
                                "user_id": 1,
                                "primary_group_id": null
                            }
                        ]
                    },
                    {
                        "id": 11,
                        "title": "Instrukcje i porady",
                        "fancy_title": "Instrukcje i porady",
                        "slug": "instrukcje-i-porady",
                        "posts_count": 1,
                        "reply_count": 0,
                        "highest_post_number": 1,
                        "image_url": null,
                        "created_at": "2020-12-07T07:30:53.850Z",
                        "last_posted_at": "2020-12-07T07:30:54.096Z",
                        "bumped": true,
                        "bumped_at": "2020-12-07T07:30:54.096Z",
                        "archetype": "regular",
                        "unseen": false,
                        "last_read_post_number": 1,
                        "unread": 0,
                        "new_posts": 0,
                        "pinned": false,
                        "unpinned": null,
                        "visible": true,
                        "closed": false,
                        "archived": false,
                        "notification_level": 3,
                        "bookmarked": false,
                        "liked": false,
                        "views": 6,
                        "like_count": 0,
                        "has_summary": false,
                        "last_poster_username": "user",
                        "category_id": 1,
                        "pinned_globally": false,
                        "featured_link": null,
                        "posters": [
                            {
                                "extras": "latest single",
                                "description": "Autor pierwszego wpisu, Autor najnowszego wpisu",
                                "user_id": 1,
                                "primary_group_id": null
                            }
                        ]
                    },
                    {
                        "id": 9,
                        "title": "README: Skrócony poradnik administratora",
                        "fancy_title": "README: Skrócony poradnik administratora",
                        "slug": "readme-skrocony-poradnik-administratora",
                        "posts_count": 1,
                        "reply_count": 0,
                        "highest_post_number": 1,
                        "image_url": null,
                        "created_at": "2020-12-06T13:09:06.589Z",
                        "last_posted_at": "2020-12-06T13:09:06.735Z",
                        "bumped": true,
                        "bumped_at": "2020-12-06T16:02:27.933Z",
                        "archetype": "regular",
                        "unseen": false,
                        "last_read_post_number": 1,
                        "unread": 0,
                        "new_posts": 0,
                        "pinned": false,
                        "unpinned": null,
                        "visible": true,
                        "closed": false,
                        "archived": false,
                        "notification_level": 1,
                        "bookmarked": false,
                        "liked": false,
                        "views": 2,
                        "like_count": 0,
                        "has_summary": false,
                        "last_poster_username": "system",
                        "category_id": 3,
                        "pinned_globally": false,
                        "featured_link": null,
                        "posters": [
                            {
                                "extras": "latest single",
                                "description": "Autor pierwszego wpisu, Autor najnowszego wpisu",
                                "user_id": -1,
                                "primary_group_id": null
                            }
                        ]
                    },
                    {
                        "id": 7,
                        "title": "Witaj w Discourse",
                        "fancy_title": "Witaj w Discourse",
                        "slug": "witaj-w-discourse",
                        "posts_count": 1,
                        "reply_count": 0,
                        "highest_post_number": 1,
                        "image_url": null,
                        "created_at": "2020-12-06T13:09:06.287Z",
                        "last_posted_at": "2020-12-06T13:09:06.342Z",
                        "bumped": true,
                        "bumped_at": "2020-12-06T16:02:27.708Z",
                        "archetype": "regular",
                        "unseen": false,
                        "last_read_post_number": 1,
                        "unread": 0,
                        "new_posts": 0,
                        "pinned": false,
                        "unpinned": true,
                        "visible": true,
                        "closed": false,
                        "archived": false,
                        "notification_level": 1,
                        "bookmarked": false,
                        "liked": false,
                        "views": 5,
                        "like_count": 0,
                        "has_summary": false,
                        "last_poster_username": "system",
                        "category_id": 1,
                        "pinned_globally": true,
                        "featured_link": null,
                        "posters": [
                            {
                                "extras": "latest single",
                                "description": "Autor pierwszego wpisu, Autor najnowszego wpisu",
                                "user_id": -1,
                                "primary_group_id": null
                            }
                        ]
                    },
                    {
                        "id": 6,
                        "title": "Polityka prywatności",
                        "fancy_title": "Polityka prywatności",
                        "slug": "polityka-prywatnosci",
                        "posts_count": 2,
                        "reply_count": 0,
                        "highest_post_number": 2,
                        "image_url": null,
                        "created_at": "2020-12-06T13:09:05.924Z",
                        "last_posted_at": "2020-12-06T13:09:06.221Z",
                        "bumped": true,
                        "bumped_at": "2020-12-06T16:02:27.642Z",
                        "archetype": "regular",
                        "unseen": false,
                        "last_read_post_number": 2,
                        "unread": 0,
                        "new_posts": 0,
                        "pinned": false,
                        "unpinned": null,
                        "visible": true,
                        "closed": false,
                        "archived": false,
                        "notification_level": 1,
                        "bookmarked": false,
                        "liked": false,
                        "views": 1,
                        "like_count": 0,
                        "has_summary": false,
                        "last_poster_username": "system",
                        "category_id": 3,
                        "pinned_globally": false,
                        "featured_link": null,
                        "posters": [
                            {
                                "extras": "latest single",
                                "description": "Autor pierwszego wpisu, Autor najnowszego wpisu",
                                "user_id": -1,
                                "primary_group_id": null
                            }
                        ]
                    },
                    {
                        "id": 5,
                        "title": "FAQ/Przewodnik",
                        "fancy_title": "FAQ/Przewodnik",
                        "slug": "faq-przewodnik",
                        "posts_count": 2,
                        "reply_count": 0,
                        "highest_post_number": 2,
                        "image_url": null,
                        "created_at": "2020-12-06T13:09:05.528Z",
                        "last_posted_at": "2020-12-06T13:09:05.838Z",
                        "bumped": true,
                        "bumped_at": "2020-12-06T16:02:27.451Z",
                        "archetype": "regular",
                        "unseen": false,
                        "last_read_post_number": 2,
                        "unread": 0,
                        "new_posts": 0,
                        "pinned": false,
                        "unpinned": null,
                        "visible": true,
                        "closed": false,
                        "archived": false,
                        "notification_level": 1,
                        "bookmarked": false,
                        "liked": false,
                        "views": 3,
                        "like_count": 0,
                        "has_summary": false,
                        "last_poster_username": "system",
                        "category_id": 3,
                        "pinned_globally": false,
                        "featured_link": null,
                        "posters": [
                            {
                                "extras": "latest single",
                                "description": "Autor pierwszego wpisu, Autor najnowszego wpisu",
                                "user_id": -1,
                                "primary_group_id": null
                            }
                        ]
                    },
                    {
                        "id": 4,
                        "title": "Warunki użytkowania",
                        "fancy_title": "Warunki użytkowania",
                        "slug": "warunki-uzytkowania",
                        "posts_count": 2,
                        "reply_count": 0,
                        "highest_post_number": 2,
                        "image_url": null,
                        "created_at": "2020-12-06T13:09:04.925Z",
                        "last_posted_at": "2020-12-06T13:09:05.455Z",
                        "bumped": true,
                        "bumped_at": "2020-12-06T16:02:27.085Z",
                        "archetype": "regular",
                        "unseen": false,
                        "last_read_post_number": 2,
                        "unread": 0,
                        "new_posts": 0,
                        "pinned": false,
                        "unpinned": null,
                        "visible": true,
                        "closed": false,
                        "archived": false,
                        "notification_level": 1,
                        "bookmarked": false,
                        "liked": false,
                        "views": 3,
                        "like_count": 0,
                        "has_summary": false,
                        "last_poster_username": "system",
                        "category_id": 3,
                        "pinned_globally": false,
                        "featured_link": null,
                        "posters": [
                            {
                                "extras": "latest single",
                                "description": "Autor pierwszego wpisu, Autor najnowszego wpisu",
                                "user_id": -1,
                                "primary_group_id": null
                            }
                        ]
                    }
                ]
            }
        }

        return of(latestTopicsResponse.topic_list.topics.slice(0, offset));
    }

    /**
     * Gets latest topics with categories
     * @param {number} [offset] 
     * @returns {Observable<ForumTopicWithCategory[]>} latest topics with categories 
     */
    getLatestTopicsWithCategories(offset?: number): Observable<ForumTopicWithCategory[]> {
        return combineLatest([this.getCategories(), this.getLatestTopics(offset)]).pipe(
            map(([categories, latestTopics]) => {
                return latestTopics.map(topic => {
                    return {
                        ...topic,
                        category: categories.find(category => category.id === topic.category_id)
                    }
                });
            })
        );
    }

    /**
     * Marks notifications as read
     */
    markNotificationsAsRead() {
        return of(true).pipe(
            delay(500)
        );
    }
}
